trigger:
  branches:
    include:
    - refs/heads/develop
name: $(date:yyyyMMdd)$(rev:.r)
parameters:
  - name: nameTaskBooleanFalse
    displayName: Type boolean False
    type: boolean
    default: False
  - name: nameTaskBooleanTrue
    displayName: Type boolean True
    type: boolean
    default: True
  - name: nameTaskValues
    displayName: Type Values
    default: Maybe
    values:
      - Yes
      - No
      - Maybe

