trigger: none
name: $(date:yyyyMMdd)$(rev:.r)
parameters:
  - name: input
    displayName: Variable Input
variables:
  - group: test_001

jobs:
- job: conditional
  steps:
  - task: PowerShell@2
    displayName: Conditional Variable By Parameters
    condition: in('${{ parameters.input }}', 'release', 'feature')
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "var_conditional_branch contains release or feature in the value"
  - task: PowerShell@2
    displayName: Conditional by Variable Group
    condition: and(succeeded(), eq($(var_conditional_branch), 'feature'))
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "var_conditional_branch contains release or feature in the value"
