trigger:
  branches:
    include:
    - refs/heads/develop
name: $(date:yyyyMMdd)$(rev:.r)
parameters:
  - name: nameTaskBooleanFalse
    displayName: Type boolean False
    type: boolean
    default: False
  - name: nameTaskBooleanTrue
    displayName: Type boolean True
    type: boolean
    default: True
  - name: nameTaskValues
    displayName: Type Values
    default: Maybe
    values:
      - Yes
      - No
      - Maybe
  - name: nameTaksInput
    displayName: Type Input
  - name: nameObjectTask
    displayName: Type Object
    type: object
    default:
      things:
      - one
      - two
      - three
  - name: nameStepTask
    displayName: Type Steps
    type: step
    default:
      script: echo my step
  - name: nameStepTaskList
    type: stepList
    default:
      - script: echo step one
      - script: echo step two

jobs: 
- job: stepList
  steps: ${{ parameters.nameStepTaskList }}
- job: myStep
  steps:
    - ${{ parameters.nameStepTask }}
- job: Object Run
steps:
- ${{ each value in parameters.nameObjectTask.things }}:
  - script: echo ${{ value }}
