
variables:
- group: release_variables
- group: build_variables

name: $(date:yyyyMMdd)$(rev:.r)

jobs:
- job: release_deploy
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo Get Latest build ID
          $url1 = "https://dev.azure.com/azureDevOpsLaboratory/Azureworshop/_apis/build/latest/$(build_definition_name_01)?branchName=$(switch_branch)&api-version=6.1-preview.1"
                  $result_buid_01 = Invoke-RestMethod -Uri $url -Headers @{
                      Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
                  }
          $url2 = "https://dev.azure.com/azureDevOpsLaboratory/Azureworshop/_apis/build/latest/$(build_definition_name_02)?branchName=$(switch_branch)&api-version=6.1-preview.1"
                  $result_buid_02 = Invoke-RestMethod -Uri $url -Headers @{
                      Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
                  }
          $url3 = "https://dev.azure.com/azureDevOpsLaboratory/Azureworshop/_apis/build/latest/$(build_definition_name_03)?branchName=$(switch_branch)&api-version=6.1-preview.1"
                  $result_buid_03 = Invoke-RestMethod -Uri $url -Headers @{
                      Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
                  }
          echo Create Build ID Variables
          $buildId_01 = $result_buid_01.id
          $buildId_02 = $result_buid_02.id
          $buildId_03 = $result_buid_03.id

          echo Create Body
          $body = @"
          {
              "definitionId": $ReleasedefinitionID,
              "description": "Release Created from ADO"
              "artifacts": [
              {
                  "alias": "api01",
                  "instanceReference": {
                      "id": "$buildId_01",
                      "name": "api01"
                  }
              },
              {
                  "alias": "api02",
                  "instanceReference": {
                      "id": "$buildId_02",
                      "name": "api02"
                  }
              },
              {
                  "alias": "api03",
                  "instanceReference": {
                      "id": "$buildId_03",
                      "name": "api03"
                  }
              }
              ],
              "idDraft": false,
              "reason": "Release created from ADO Build Pipeline",
              "manualEnvironments": null
          }
          "@
            $contentType = 'application/json'
            $url = "https://vsrm.dev.azure.com/{organization}/{project}/_apis/release/releases?api-version=6.1-preview.8"
            $executeCommand= Invoke-RestMethod -Uri $url -Method POST -Body $body -ContenType $contentType -Headers @{
                Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
            }
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
...